/**
 * M0.2: what the Paged.js baseline says, checked deterministically.
 *
 * The baseline is generated by `packages/test/baseline.mjs`, which needs a
 * browser. This test needs only the file it wrote, so the properties of
 * `doc/plan.md` §9 are checked in layer 1 — fast, no browser, and the same
 * assertions our own engine will face from M1.
 */
import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { contentCheck, pageCounts } from "./placement.js";
import type { CorpusResult } from "./placement.js";

const BASELINE = new URL("../baselines/pagedjs-chromium.json", import.meta.url).pathname;

type Baseline = {
  environment: { engine: string; engineVersion: string; fontsArePinned: boolean };
  pagedjs: string;
  results: CorpusResult[];
  failures: { spec: string; error: string }[];
};

const baseline: Baseline | null = existsSync(BASELINE)
  ? (JSON.parse(readFileSync(BASELINE, "utf8")) as Baseline)
  : null;

describe.skipIf(baseline === null)("the Paged.js baseline", () => {
  const b = baseline as Baseline;

  it("covers the whole corpus", () => {
    expect(b.results.length).toBeGreaterThan(100);
    expect(b.failures, "fixtures that would not paginate").toEqual([]);
  });

  it("paginates every fixture to at least one page", () => {
    const empty = b.results.filter((r) => r.pageCount === 0);
    expect(empty.map((r) => r.spec)).toEqual([]);
  });

  it("says which specs lose content, and which merely repeat it", () => {
    // Not an assertion about us, and not a failure: plan.md §9 asks for the
    // content property, and running it against the baseline is how we learn
    // which corpus specs can serve as evidence at all.
    //
    // Loss and repetition are separated because only one of them is a defect.
    // A repeated <thead>, a fixed-position element and generated content all
    // put the same source characters on several pages by design, so "exactly
    // once" holds for *flowed* content, not for every character on the page.
    // That refinement was found here, against real output (M0.2).
    const lost: string[] = [];
    const repeated: string[] = [];
    for (const r of b.results) {
      const failures = contentCheck(r);
      if (failures.some((f) => f.paginated < f.source)) lost.push(r.spec);
      else if (failures.length > 0) repeated.push(r.spec);
    }

    expect({ lost: lost.sort(), repeated: repeated.sort() }).toMatchSnapshot();
  });

  it("records page counts for the differential comparison", () => {
    const counts = pageCounts(b.results);
    expect(Object.keys(counts)).toHaveLength(b.results.length);
    expect(counts["specs/widows-orphans/widows-orphans.html"]).toBeGreaterThan(0);
  });

  it("is honest that its page counts are not portable", () => {
    // 41 corpus fixtures name a font-family and none loads a webfont, so every
    // page count is a function of this machine's installed fonts. Layer 4 has
    // to compare the two engines inside one run; this file is a record of one
    // environment, not an expectation another machine can be held to.
    expect(b.environment.fontsArePinned).toBe(false);
    expect(b.environment.engineVersion).toMatch(/\d+\./);
  });
});
